/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CachedRouterView: typeof import('./components/CachedRouterView.vue')['default']
    CheckinCelebrate: typeof import('./components/CheckinCelebrate.vue')['default']
    CheckinDrawer: typeof import('./components/CheckinDrawer.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    FocusTimer: typeof import('./components/FocusTimer.vue')['default']
    JournalSoftTip: typeof import('./components/JournalSoftTip.vue')['default']
    LoginCodeQr: typeof import('./components/LoginCodeQr.vue')['default']
    MonitorChildCard: typeof import('./components/MonitorChildCard.vue')['default']
    MonitorChildFilter: typeof import('./components/MonitorChildFilter.vue')['default']
    MonitorFamilyFeed: typeof import('./components/MonitorFamilyFeed.vue')['default']
    MonitorInsightStrip: typeof import('./components/MonitorInsightStrip.vue')['default']
    MonitorPendingPanel: typeof import('./components/MonitorPendingPanel.vue')['default']
    MonitorWeekendBanner: typeof import('./components/MonitorWeekendBanner.vue')['default']
    OnboardingWizard: typeof import('./components/OnboardingWizard.vue')['default']
    PageSkeleton: typeof import('./components/PageSkeleton.vue')['default']
    ParentTaskEditDrawer: typeof import('./components/ParentTaskEditDrawer.vue')['default']
    ParentTaskFormFields: typeof import('./components/ParentTaskFormFields.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoftPrompt: typeof import('./components/SoftPrompt.vue')['default']
    SoftStay: typeof import('./components/SoftStay.vue')['default']
    ThemeWeekDrawer: typeof import('./components/ThemeWeekDrawer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
