import {
  TaskCategory,
  TaskSchedule,
  TargetType,
  TimeSlot,
} from '../common/enums';

export type TaskTemplate = {
  id: string;
  title: string;
  description: string;
  category: TaskCategory;
  timeSlot: TimeSlot;
  schedule: TaskSchedule;
  targetType: TargetType;
  targetValue: number;
  pointsReward: number;
  requireConfirm: boolean;
  isInterest?: boolean;
  meaningNote?: string;
};

export const TASK_TEMPLATES: TaskTemplate[] = [
  {
    id: 'study-read',
    title: '每日阅读 20 分钟',
    description: '朗读或默读均可',
    category: TaskCategory.STUDY,
    timeSlot: TimeSlot.AFTER_SCHOOL,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.DURATION,
    targetValue: 20,
    pointsReward: 10,
    requireConfirm: false,
    isInterest: true,
    meaningNote: '读进去，故事会在脑子里变得更完整',
  },
  {
    id: 'interest-explore',
    title: '兴趣探索 15 分钟',
    description: '画画、搭积木、观察自然或动手小实验，任选一件',
    category: TaskCategory.STUDY,
    timeSlot: TimeSlot.AFTER_SCHOOL,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.DURATION,
    targetValue: 15,
    pointsReward: 8,
    requireConfirm: false,
    isInterest: true,
    meaningNote: '跟着好奇走一会儿，比强迫更有力量',
  },
  {
    id: 'study-words',
    title: '背单词 15 个',
    description: '可默写或口头检查',
    category: TaskCategory.STUDY,
    timeSlot: TimeSlot.AFTER_DINNER,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.COUNT,
    targetValue: 15,
    pointsReward: 10,
    requireConfirm: false,
  },
  {
    id: 'study-instrument',
    title: '练琴 / 乐器 20 分钟',
    description: '按老师布置练习',
    category: TaskCategory.STUDY,
    timeSlot: TimeSlot.AFTER_SCHOOL,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.DURATION,
    targetValue: 20,
    pointsReward: 10,
    requireConfirm: false,
  },
  {
    id: 'chore-desk',
    title: '整理自己的书桌',
    description: '书本归位，桌面干净',
    category: TaskCategory.CHORE,
    timeSlot: TimeSlot.AFTER_SCHOOL,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 5,
    requireConfirm: false,
  },
  {
    id: 'chore-dishes',
    title: '饭后收拾碗筷',
    description: '把碗筷送到厨房或帮忙清洗',
    category: TaskCategory.CHORE,
    timeSlot: TimeSlot.AFTER_DINNER,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 8,
    requireConfirm: false,
  },
  {
    id: 'chore-trash',
    title: '倒垃圾',
    description: '把家里垃圾袋送到楼下',
    category: TaskCategory.CHORE,
    timeSlot: TimeSlot.AFTER_DINNER,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 5,
    requireConfirm: false,
  },
  {
    id: 'chore-clothes',
    title: '叠好今天的衣服',
    description: '自己的衣物叠整齐放好',
    category: TaskCategory.CHORE,
    timeSlot: TimeSlot.BEDTIME,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 5,
    requireConfirm: false,
  },
  {
    id: 'chore-plant',
    title: '给绿植浇水',
    description: '适量浇水，不要积水',
    category: TaskCategory.CHORE,
    timeSlot: TimeSlot.AFTER_SCHOOL,
    schedule: TaskSchedule.WEEKLY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 5,
    requireConfirm: false,
  },
  {
    id: 'routine-brush',
    title: '刷牙洗脸',
    description: '睡前认真刷牙',
    category: TaskCategory.ROUTINE,
    timeSlot: TimeSlot.BEDTIME,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 3,
    requireConfirm: false,
  },
  {
    id: 'routine-make-bed',
    title: '起床叠被子',
    description: '起床后把被子叠整齐',
    category: TaskCategory.ROUTINE,
    timeSlot: TimeSlot.AFTER_WAKE,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 3,
    requireConfirm: false,
  },
  {
    id: 'routine-pack-bag',
    title: '收拾书包',
    description: '按课表装好书本和文具',
    category: TaskCategory.ROUTINE,
    timeSlot: TimeSlot.BEFORE_SCHOOL,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 5,
    requireConfirm: false,
  },
  {
    id: 'routine-bag',
    title: '收拾明天的书包',
    description: '按课表装好书本和文具',
    category: TaskCategory.ROUTINE,
    timeSlot: TimeSlot.BEDTIME,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 5,
    requireConfirm: false,
  },
  {
    id: 'routine-bed',
    title: '整理床铺',
    description: '起床后把被子叠好',
    category: TaskCategory.ROUTINE,
    timeSlot: TimeSlot.ANYTIME,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 3,
    requireConfirm: false,
  },
  // —— 情商与生活能力 ——
  {
    id: 'eq-mood',
    title: '说出今天的心情',
    description: '用一句话告诉家人：今天开心/难过/紧张…（过程赞：敢表达）',
    category: TaskCategory.ROUTINE,
    timeSlot: TimeSlot.AFTER_DINNER,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 5,
    requireConfirm: false,
  },
  {
    id: 'eq-thanks',
    title: '感谢家人一件事',
    description: '当面或写纸条感谢爸爸/妈妈/家人今天帮了你什么',
    category: TaskCategory.ROUTINE,
    timeSlot: TimeSlot.AFTER_DINNER,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 5,
    requireConfirm: false,
  },
  {
    id: 'eq-listen',
    title: '认真听对方说完',
    description: '和家人聊天时，先听完再回应（练习同理心）',
    category: TaskCategory.ROUTINE,
    timeSlot: TimeSlot.ANYTIME,
    schedule: TaskSchedule.WEEKLY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 8,
    requireConfirm: false,
  },
  {
    id: 'life-laundry',
    title: '把自己的脏衣服放进洗衣篮',
    description: '生活自理一小步',
    category: TaskCategory.CHORE,
    timeSlot: TimeSlot.BEDTIME,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.ONCE,
    targetValue: 1,
    pointsReward: 3,
    requireConfirm: false,
  },
  {
    id: 'life-time',
    title: '自己定一个 10 分钟小目标',
    description: '例如专注写作业/收拾书桌，到点就停（时间管理）',
    category: TaskCategory.ROUTINE,
    timeSlot: TimeSlot.AFTER_SCHOOL,
    schedule: TaskSchedule.DAILY,
    targetType: TargetType.DURATION,
    targetValue: 10,
    pointsReward: 5,
    requireConfirm: false,
  },
];
